services:
  web:
    command: streamlit run UI.py
    image: usmankhalidst125051/assignment_three:v2.0
    platform: linux/x84_64
    build:
      context: .
      dockerfile: .Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=80
    ports:
      - 4000:80
  