name: Build-Test
run-name: ${{ github.actor }} Building and Testing

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: usmankhalidst125051/cara3
          tags: |
            type=sha,format=long
            type=ref,event=branch
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./.streamlit
          file: Dockerfile.streamlit
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            tag=${{ github.sha }} docker compose -f st125051/docker-compose.yaml down
            tag=${{ github.sha }} docker compose -f st125051/docker-compose.yaml up -d
